{
  "config": [
    "user_data/config.json"
  ],
  "user_data_dir": "user_data",
  "strategy": "SampleStrategy",
  "timeframe": "4h",
  "timerange": "20210101-20240326",
  "max_open_trades": 5,
  "stake_amount": "unlimited",
  "dry_run_wallet": 1000,
  "enable_protections": false,
  "position_stacking": false,
  "disableparamexport": true,
  "epochs": 6400,
  "hyperopt_jobs": 32,
  "hyperopt_loss": "SortinoHyperOptLossDaily",
  "hyperopt_min_trades": 300,
  "print_all": true,
  "spaces": [
    "buy",
    "sell"
  ],
  "max_generated_candidates": 250,
  "max_parallel_backtest": 8,
  "pipelines": [
    {
      "id": "generate_00",
      "type": "hyperopt_generate",
      "spaces": [
        "buy",
        "stoploss",
        "roi"
      ]
    },
    {
      "id": "optim_00",
      "type": "hyperopt_optimize",
      "epochs": 256,
      "timeframe_detail": "1h",
      "spaces": [
        "stoploss",
        "roi"
      ]
    },
    {
      "id": "optim_01",
      "type": "hyperopt_optimize",
      "epochs": 256,
      "timeframe_detail": "1h",
      "spaces": [
        "trailing"
      ]
    },
    {
      "id": "testing_00",
      "type": "backtesting",
      "timeframe_detail": "15m",
      "timerange": "20230701-20231001"
    },
    {
      "id": "testing_01",
      "type": "backtesting",
      "timeframe_detail": "15m",
      "timerange": "20231001-20240101"
    },
    {
      "id": "testing_02",
      "type": "backtesting",
      "timeframe_detail": "5m",
      "timerange": "20240101-20240401"
    }
  ]
}
