# FREQTRADE CONFIG
strategy: "SampleStrategy"
userdir: "user_data"
config: "user_data/config.json"
timeframe: "4h"
timerange: "20230701-20240101"
max_open_trades: 10
dry_run_wallet: 0.1
stake_amoung: "unlimited"
min_trades: 100
job_workers: -1
epochs: 64
hyperopt_loss: "SortinoHyperOptLossDaily"


# AUTO-HYPEROPT CONFIG
max_generated_strategies: 20
max_parallel_backtest: 8

generate:
  spaces:
    - buy
    - sell

finetune_0:
  epochs: 32
  timeframe_detail: "5m"
  hyperopt_loss: "SortinoHyperOptLossDaily"
  spaces:
    - roi
    - stoploss

finetune_1:
  epochs: 32
  timeframe_detail: "5m"
  hyperopt_loss: "SharpeHyperOptLossDaily"
  spaces:
    - trailing

backtest:
  timeframe_detail: "5m"
  timerange: "20231201-20240101"

